In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import glob
import os
from datetime import datetime
from datetime import timedelta
import rioxarray as rxr
import rasterio
from rasterio.plot import plotting_extent
import geopandas as gpd
# Rasterstats contains the zonalstatistics function
# that you will use to extract raster values
import rasterstats as rs
import earthpy as et
import earthpy.plot as ep

In [9]:
forestdir = "/work/tadesse/beichen/Work/ForestDri/Ameriflux/western_forests/"
shrubdir = "/work/tadesse/beichen/Work/ForestDri/Ameriflux/western_shrublands/"

forestlist = glob.glob(forestdir+"*.csv")
forestlist.sort()
print(len(forestlist))
shrublist = glob.glob(shrubdir+"*.csv")
shrublist.sort()
print(len(shrublist))

9
6

In [10]:
forestlist

['/work/tadesse/beichen/Work/ForestDri/Ameriflux/western_forests/AMF_US-CMW_BASE_HH_2-5.csv',
 '/work/tadesse/beichen/Work/ForestDri/Ameriflux/western_forests/AMF_US-GLE_BASE_HH_8-5.csv',
 '/work/tadesse/beichen/Work/ForestDri/Ameriflux/western_forests/AMF_US-Me2_BASE_HH_17-5.csv',
 '/work/tadesse/beichen/Work/ForestDri/Ameriflux/western_forests/AMF_US-Mpj_BASE_HH_15-5.csv',
 '/work/tadesse/beichen/Work/ForestDri/Ameriflux/western_forests/AMF_US-NR1_BASE_HH_17-5.csv',
 '/work/tadesse/beichen/Work/ForestDri/Ameriflux/western_forests/AMF_US-Uaf_BASE_HH_8-5.csv',
 '/work/tadesse/beichen/Work/ForestDri/Ameriflux/western_forests/AMF_US-Vcm_BASE_HH_17-5.csv',
 '/work/tadesse/beichen/Work/ForestDri/Ameriflux/western_forests/AMF_US-Vcp_BASE_HH_13-5.csv',
 '/work/tadesse/beichen/Work/ForestDri/Ameriflux/western_forests/AMF_US-Wrc_BASE_HH_8-1.csv']

In [ ]:
with open(forestlist[0], 'r') as f:
    lines = f.readlines()
    print(lines[:1000])

In [11]:
cleaned_fdir = "/work/tadesse/beichen/Work/ForestDri/Ameriflux/cleaned_western/"

In [12]:
for f in forestlist:
    site_name = "US_"+os.path.basename(f)[:-4].split("-")[1][:3]
    df = pd.read_csv(f, sep = "\n", header = None).iloc[2:,0]
    df_split = df.str.split(",",expand=True)
    df_split.to_csv(cleaned_fdir+site_name+".csv", header = None, index = None, sep = ',')

In [8]:
for s in shrublist:
    site_name = "US_"+os.path.basename(s)[:-4].split("-")[1][:3]
    df = pd.read_csv(s, sep = "\n", header = None).iloc[2:,0]
    df_split = df.str.split(",",expand=True)
    df_split.to_csv(cleaned_fdir+site_name+".csv", header = None, index = None, sep = ',')

In [13]:
cleaned_flist = glob.glob(cleaned_fdir+"*.csv")
cleaned_flist.sort()

In [14]:
cleaned_flist

['/work/tadesse/beichen/Work/ForestDri/Ameriflux/cleaned_western/US_CMW.csv',
 '/work/tadesse/beichen/Work/ForestDri/Ameriflux/cleaned_western/US_GLE.csv',
 '/work/tadesse/beichen/Work/ForestDri/Ameriflux/cleaned_western/US_Me2.csv',
 '/work/tadesse/beichen/Work/ForestDri/Ameriflux/cleaned_western/US_Mpj.csv',
 '/work/tadesse/beichen/Work/ForestDri/Ameriflux/cleaned_western/US_NR1.csv',
 '/work/tadesse/beichen/Work/ForestDri/Ameriflux/cleaned_western/US_SRM.csv',
 '/work/tadesse/beichen/Work/ForestDri/Ameriflux/cleaned_western/US_Ses.csv',
 '/work/tadesse/beichen/Work/ForestDri/Ameriflux/cleaned_western/US_Ton.csv',
 '/work/tadesse/beichen/Work/ForestDri/Ameriflux/cleaned_western/US_Uaf.csv',
 '/work/tadesse/beichen/Work/ForestDri/Ameriflux/cleaned_western/US_Vcm.csv',
 '/work/tadesse/beichen/Work/ForestDri/Ameriflux/cleaned_western/US_Vcp.csv',
 '/work/tadesse/beichen/Work/ForestDri/Ameriflux/cleaned_western/US_Whs.csv',
 '/work/tadesse/beichen/Work/ForestDri/Ameriflux/cleaned_western/US_Wjs.csv',
 '/work/tadesse/beichen/Work/ForestDri/Ameriflux/cleaned_western/US_Wrc.csv']

In [16]:
for f in cleaned_flist[:2]:
    fname = os.path.basename(f)[:-4]
    print(fname)
    df = pd.read_csv(f)
    df_na = df.replace([-9999], np.nan)
    if ['LE'] in df_na.columns.values:
        df_dropna = df_na.dropna(subset = ['H','LE'],axis = 0)
        df_dropna_out = df_dropna.loc[:,['TIMESTAMP_START', 'TIMESTAMP_END','LE','H']]
        df_dropna_out = df_dropna_out.rename(columns={"TIMESTAMP_START": "TIMESTAMP_START", "TIMESTAMP_END": "TIMESTAMP_END", "LE": "LE",
                                     "H": "H"})
        df_dropna_out.to_csv("/work/tadesse/beichen/Work/ForestDri/Ameriflux/HLE_sites_western/"+fname+"_LEH.csv", index=None)
    elif ['LE_1_1_1'] in df_na.columns.values:
        df_dropna = df_na.dropna(subset = ['H_1_1_1','LE_1_1_1'],axis = 0)
        df_dropna_out = df_dropna.loc[:,['TIMESTAMP_START', 'TIMESTAMP_END','LE_1_1_1','H_1_1_1']]
        df_dropna_out = df_dropna_out.rename(columns={"TIMESTAMP_START": "TIMESTAMP_START", "TIMESTAMP_END": "TIMESTAMP_END", "LE_1_1_1": "LE",
                                     "H_1_1_1": "H"})
        df_dropna_out.to_csv("/work/tadesse/beichen/Work/ForestDri/Ameriflux/HLE_sites_western/"+fname+"_LEH.csv", index=None)
    else:
        print(df.columns)

US_CMW
US_GLE

In [13]:
df.columns

Index(['TIMESTAMP_START', 'TIMESTAMP_END', 'USTAR', 'TA', 'WD', 'WS', 'NEE_PI',
       'FC', 'SC', 'H', 'SH', 'LE', 'SLE', 'G', 'TS_1', 'TS_2', 'P', 'RH',
       'PA', 'CO2_1', 'CO2_2', 'VPD_PI', 'SWC_1', 'SWC_2', 'NETRAD', 'PPFD_IN',
       'SW_IN', 'SW_DIF', 'PPFD_OUT', 'SW_OUT', 'LW_IN', 'LW_OUT', 'H2O',
       'RECO_PI', 'APAR', 'PPFD_DIF', 'FAPAR', 'ZL'],
      dtype='object')

In [ ]:
df = pd.read_csv("/work/tadesse/beichen/Work/ForestDri/Ameriflux/cleaned_western/US_Mpj.csv")
for i in df.columns:
    if "TA_" in i:
        print(i)

In [4]:
df = pd.read_csv("/work/tadesse/beichen/Work/ForestDri/Ameriflux/cleaned_western/US_GLE.csv")
for i in df.columns:
    if "LE_" in i:
        print(i)
    elif "H_" in i:
        print(i)

RH_PI_F_1_1_1
RH_1_1_1
H_PI_F_1_1_1
H_1_1_1
LE_PI_F_1_1_1
LE_1_1_1
LE_1_1_2
RH_1_2_1
H_PI_F_1_2_1
H_1_2_1
LE_PI_F_1_2_1
LE_1_2_1
RH_PI_F_2_1_1
RH_2_1_1
H_PI_F_2_1_1
H_2_1_1
LE_PI_F_2_1_1
LE_2_1_1
LE_PI_F_2_1_2
LE_2_1_2
LE_PI_F_2_1_3
LE_2_1_3

In [19]:
df = pd.read_csv("/work/tadesse/beichen/Work/ForestDri/Raw_Data/Ameriflux/cleaned_western/US_GLE.csv")
for i in df.columns:
    if "LE_" in i:
        print(i)
    elif "H_" in i:
        print(i)

RH_PI_F_1_1_1
RH_1_1_1
H_PI_F_1_1_1
H_1_1_1
LE_PI_F_1_1_1
LE_1_1_1
LE_1_1_2
RH_1_2_1
H_PI_F_1_2_1
H_1_2_1
LE_PI_F_1_2_1
LE_1_2_1
RH_PI_F_2_1_1
RH_2_1_1
H_PI_F_2_1_1
H_2_1_1
LE_PI_F_2_1_1
LE_2_1_1
LE_PI_F_2_1_2
LE_2_1_2
LE_PI_F_2_1_3
LE_2_1_3

In [20]:
df = pd.read_csv("/work/tadesse/beichen/Work/ForestDri/Raw_Data/Ameriflux/cleaned_western/US_Ton.csv")
for i in df.columns:
    if "LE_" in i:
        print(i)
    elif "H_" in i:
        print(i)

LE_1_1_1
H_1_1_1
RH_1_1_1
LE_PI_F_1_1_1
H_PI_F_1_1_1
RH_PI_F_1_1_1
LE_1_2_1
H_1_2_1
RH_1_2_1
LE_PI_F_1_2_1
H_PI_F_1_2_1

In [17]:
#test
#original file
df_CMW = pd.read_csv("/work/tadesse/beichen/Work/ForestDri/Ameriflux/cleaned_western/US_CMW.csv")
df_CMW.head()

,TIMESTAMP_START,TIMESTAMP_END,NETRAD,G,LE,H,FC,USTAR,CO2,H2O,...,SWC_PI_2_1_A,TS_1_1_1,TS_1_2_1,TS_1_3_1,TS_1_4_1,TS_1_5_1,TS_1_6_1,NEE_PI,RECO_PI,GPP_PI
0,200001010000,200001010030,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
1,200001010030,200001010100,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
2,200001010100,200001010130,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
3,200001010130,200001010200,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
4,200001010200,200001010230,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0

In [18]:
df_CMW.tail()

,TIMESTAMP_START,TIMESTAMP_END,NETRAD,G,LE,H,FC,USTAR,CO2,H2O,...,SWC_PI_2_1_A,TS_1_1_1,TS_1_2_1,TS_1_3_1,TS_1_4_1,TS_1_5_1,TS_1_6_1,NEE_PI,RECO_PI,GPP_PI
385722,202112312100,202112312130,-4.053,-12.470453,-9999.000000,-22.076771,-9999.000000,0.206104,-9999.000000,-9999.000000,...,4.914388,9.93,9.93,9.52,10.09,-9999.0,-9999.0,0.315953,0.315953,0.000000
385723,202112312130,202112312200,-2.546,-11.279961,49.695099,-28.689182,-9999.000000,0.212550,378.326192,12.337755,...,4.920254,9.83,9.83,9.54,10.11,-9999.0,-9999.0,0.666846,0.666846,0.000000
385724,202112312200,202112312230,-1.747,-12.528206,64.141437,-53.629200,4.337252,0.318940,408.818289,10.320559,...,4.924041,9.76,9.76,9.58,10.14,-9999.0,-9999.0,0.331742,0.331742,0.000000
385725,202112312230,202112312300,-1.634,-13.266383,44.420652,-42.655748,5.323754,0.296623,415.655305,9.528287,...,4.930479,9.67,9.67,9.59,10.15,-9999.0,-9999.0,7.357749,7.357749,0.000000
385726,202112312300,202112312330,-1.685,-11.374524,74.084150,-41.870109,-1.054417,0.361145,412.074884,11.377966,...,4.898596,9.58,9.58,9.60,10.17,-9999.0,-9999.0,-2.043043,0.331024,2.374067

In [147]:
df_CMW.loc[(df_CMW['LE']!=-9999)&(df_CMW['H']!=-9999),['TIMESTAMP_START', 'TIMESTAMP_END','LE','H']].head()

       TIMESTAMP_START  TIMESTAMP_END        LE        H
21673     200103271230   200103271300   95.2741  434.896
21674     200103271300   200103271330  132.1890  415.124
21675     200103271330   200103271400   94.9199  412.148
21678     200103271500   200103271530   64.2944  252.656
21679     200103271530   200103271600   65.1697  282.725

In [21]:
df_CMW_HLE = pd.read_csv("/work/tadesse/beichen/Work/ForestDri/Ameriflux/HLE_sites_western/US_CMW_LEH.csv")
df_CMW_HLE_50 = df_CMW_HLE.loc[(df_CMW_HLE['LE']>50)&(df_CMW_HLE['H']>50),:]
df_CMW_HLE_50.to_csv("/work/tadesse/beichen/Work/ForestDri/Ameriflux/HLE_sites_western/US_CMW_LEH_50.csv", index=False)

In [23]:
HLE_sites = "/work/tadesse/beichen/Work/ForestDri/Ameriflux/HLE_sites_western/"

In [5]:
HLE_sites = "/work/tadesse/beichen/Work/ForestDri/Ameriflux/HLE_sites_western/"
HLE_list = glob.glob(HLE_sites+"*LEH.csv")
HLE_list.sort()
for HLE in HLE_list:
    fname = os.path.basename(HLE)[:-4]
    print(fname)
    df = pd.read_csv(HLE)
    df_50 = df.loc[(df['LE']>50)&(df['H']>50),:]
    df_50.to_csv(HLE_sites+fname+"_50.csv", index=False)

US_CMW_LEH
US_GLE_LEH
US_Me2_LEH
US_Mpj_LEH
US_NR1_LEH
US_SRM_LEH
US_Ses_LEH
US_Ton_LEH
US_Uaf_LEH
US_Vcm_LEH
US_Vcp_LEH
US_Whs_LEH
US_Wjs_LEH
US_Wrc_LEH

In [24]:
HLE50_sites = "/work/tadesse/beichen/Work/ForestDri/Raw_Data/Ameriflux/HLE_sites_western/"
HLE50_list = glob.glob(HLE_sites+"*50.csv")
HLE50_list.sort()
for HLE50 in HLE50_list:
    fname = os.path.basename(HLE50)[:-11]
    print(fname)
    df = pd.read_csv(HLE50)
    df['TIMESTAMP_START'] = df['TIMESTAMP_START'].map(lambda x: int(datetime.strptime(str(x)[:8], "%Y%m%d").strftime("%Y%j")[:4])*100+int(datetime.strptime(str(x)[:8], "%Y%m%d").strftime("%Y%j")[-3:])//7+1)
    start_year = df.TIMESTAMP_START.values[0]//100
    end_year = df.TIMESTAMP_START.values[-1]//100
    print(start_year,end_year)
    weekly_index = []
    for i in range(start_year,end_year+1):
        for j in range(1,53):
            if j<10:
                j='0'+str(j)
            else:
                j=str(j)
            out = int(str(i)+str(j))
            weekly_index.append(out)
    df_out = pd.DataFrame(np.nan,index = weekly_index, columns = ["LE","H"])
    df = df.drop(['TIMESTAMP_END'],axis = 1)
    df = df.groupby('TIMESTAMP_START').sum()
    for idx in df.index.values:
        df_out.loc[idx,:]=df.loc[idx,:].values
    df_out = df_out.iloc[:(end_year-start_year+1)*52,:]
    df_out["Bowen_ratio"] = df_out.loc[:,"H"].values/df_out.loc[:,"LE"].values
    df_out["Log_Bowen_ratio"] = np.log10(df_out.loc[:,"Bowen_ratio"].values)
    reshaped_logbr = df_out.Log_Bowen_ratio.values.reshape(end_year-start_year+1,52)
    mean=np.nanmean(reshaped_logbr, axis = 0)
    std = np.nanstd(reshaped_logbr, axis = 0)
    std_logbr = (mean - reshaped_logbr)/std
    df_out["STD_Log_Bowen_ratio"] = std_logbr.flatten()
    #log_bowen = np.log10(df.loc[:,"Bowen_ratio"].values)
    #print(log_bowen.shape)
    #np.mean(log_bowen)
    #df["std_Bowen_ratio"] = ( - log_bowen)/np.std(log_bowen)
    #print(df.head())
    #df.to_csv("/work/tadesse/beichen/Work/ForestDri/Raw_Data/Ameriflux/Bowen_Ratio/"+fname+"_BW.csv")
    df_out.to_csv("/work/tadesse/beichen/Work/ForestDri/Ameriflux/Bowen_Ratio/"+fname+"_stdBW.csv")

US_CMW
2001 2021
US_GLE
2004 2020
US_Me2
2002 2021
US_Mpj
2008 2021
US_NR1
1998 2020
US_SRM
2004 2020
US_Ses
2007 2021
US_Ton
2001 2020
US_Uaf
2003 2020

/home/tadesse/beichen/.conda/envs/my_root/lib/python3.6/site-packages/ipykernel_launcher.py:30: RuntimeWarning: Mean of empty slice
/home/tadesse/beichen/.conda/envs/my_root/lib/python3.6/site-packages/numpy/lib/nanfunctions.py:1628: RuntimeWarning: Degrees of freedom <= 0 for slice.
  keepdims=keepdims)
/home/tadesse/beichen/.conda/envs/my_root/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in true_divide

US_Vcm
2007 2021
US_Vcp
2007 2021
US_Whs
2007 2020
US_Wjs
2007 2021
US_Wrc
1998 2015

In [150]:
df_out.loc[200302,:]

LE                     1220.948000
H                      2516.032000
Bowen_ratio               2.060720
Log_Bowen_ratio           0.314019
STD_Log_Bowen_ratio      -0.873576
Name: 200302, dtype: float64

In [25]:
df

                        LE          H
TIMESTAMP_START
199821             220.000    587.860
199822            3595.000   3938.783
199824            1858.000   4379.546
199825            6833.000  10692.381
199826            4029.000   7056.649
199827            1320.000   3736.529
199828            4843.000  16028.318
199829            3085.000   9911.268
199830            2963.000   9995.662
199831            4220.000  11700.883
199832            9177.000  20657.268
199833           13204.000  22464.775
199834            9669.000  17902.244
199835           11452.000  17102.607
199836            9537.000  15919.580
199837            5593.000   8944.171
199838            6259.000   6818.072
199839            7218.000   7306.501
199840            3459.000   2218.227
199841             372.000    135.832
199842            5080.000   2734.786
199843            4326.000   2834.745
199844            1458.000   1151.769
199845             320.000    166.993
199846              82.000     51.464
199848             355.000    307.224
199850             156.000    140.642
199851            2136.000   1787.139
199852            1212.000    756.316
199902             346.000    328.046
...                    ...        ...
201514            9568.843   9642.266
201515            6798.803   9780.078
201516           13216.436  22245.381
201517           10570.366  16644.475
201518           14110.407  26796.379
201519           10619.917  17724.529
201520           12113.020  18529.516
201521           10975.325  24338.209
201522           15155.217  22355.068
201523           19857.600  32567.636
201524           18209.520  40168.316
201525           18770.949  37745.199
201526           23350.007  27207.510
201527           22494.743  34500.649
201528           18697.082  29559.302
201529           16714.618  36686.686
201530           12575.591  27842.793
201531           11996.788  21891.035
201532           11039.383  26284.569
201533            9770.499  20668.536
201534            5576.466  14580.222
201535            3202.495   5242.241
201536            4779.332   7541.712
201537            3182.609   5818.853
201538            6047.900   9043.730
201539            2092.913   3839.106
201540            1850.763   3753.739
201541            2471.720   2725.436
201542             936.782   1030.530
201543            1939.255   1518.982

[752 rows x 2 columns]

In [67]:
df_out["Bowen_ratio"] = df_out.loc[:,"H"].values/df_out.loc[:,"LE"].values
df_out["Log_Bowen_ratio"] = np.log10(df_out.loc[:,"Bowen_ratio"].values)
reshaped_logbr = df_out.Log_Bowen_ratio.values.reshape(end_year-start_year+1,52)
mean=np.nanmean(reshaped_logbr, axis = 0)
std = np.nanstd(reshaped_logbr, axis = 0)
std_logbr = (mean - reshaped_br)/std
df_out["STD_Log_Bowen_ratio"] = std_logbr.flatten()

In [87]:
df_out.dropna()

,LE,H,Bowen_ratio,Log_Bowen_ratio,STD_Log_Bowen_ratio
200443,4228.612928,6905.394404,1.633016,0.212991,0.903324
200444,4183.615154,5666.505393,1.354452,0.131764,1.604489
200445,3338.282579,7071.008886,2.118158,0.325958,0.403963
200446,1939.610689,2696.260124,1.390104,0.143047,0.921783
200447,1235.421814,537.551110,0.435115,-0.361396,2.842478
200448,4301.367243,5980.776166,1.390436,0.143151,1.492505
200449,4714.868469,8341.575062,1.769206,0.247778,0.689467
200450,1195.732931,2752.113051,2.301612,0.362032,-0.261845
200452,1300.655071,3753.192989,2.885617,0.460239,-1.633145
200453,213.152481,157.834861,0.740479,-0.130487,2.028449
200501,1555.693699,1452.924682,0.933940,-0.029681,1.323847
200502,2558.713895,4776.345307,1.866698,0.271074,-0.159037
200503,5916.694085,7988.605175,1.350181,0.130392,0.911966
200504,1889.536151,3425.368841,1.812809,0.258352,0.060314
200505,464.692877,1234.032136,2.655587,0.424160,-0.665299
200506,2093.115777,4044.075664,1.932084,0.286026,0.193139
200507,5536.885354,8893.975340,1.606314,0.205830,0.874451
200508,7611.419787,13453.925223,1.767597,0.247383,0.803096
200509,6873.914629,13332.014944,1.939508,0.287692,1.330500
200510,1324.462181,4343.860831,3.279717,0.515836,-0.501839
200511,7588.679918,18424.496467,2.427892,0.385229,0.306335
200512,10051.101752,14987.331386,1.491113,0.173511,1.733258
200513,9015.056355,21814.279856,2.419761,0.383772,0.609080
200514,7088.357358,22145.461630,3.124202,0.494739,-0.353522
200515,5380.462908,14467.564290,2.688907,0.429576,0.527071
200516,3959.136302,13821.769085,3.491107,0.542963,-0.675728
200517,8255.271709,14557.516498,1.763421,0.246356,1.205060
200518,12204.561610,22097.692128,1.810609,0.257825,1.433602
200519,9169.260332,23307.177308,2.541882,0.405155,0.308336
200520,3490.130028,6119.282398,1.753311,0.243859,1.625269
...,...,...,...,...,...
202011,3591.112475,9864.060442,2.746798,0.438827,-0.022306
202012,4026.469477,11005.107695,2.733190,0.436670,0.449866
202013,4626.913849,10713.494630,2.315473,0.364640,0.742847
202014,3598.974066,13870.137024,3.853914,0.585902,-0.871042
202015,3745.531439,18161.459254,4.848834,0.685637,-0.821783
202016,7554.927250,19840.787274,2.626205,0.419329,0.309473
202017,6376.760778,21199.842765,3.324547,0.521733,-0.275422
202018,3399.497247,10092.818955,2.968915,0.472598,-0.219469
202019,5746.079897,23523.994399,4.093921,0.612139,-1.172904
202020,5038.202070,12953.805097,2.571117,0.410122,0.539722
202021,6182.407795,19484.310327,3.151573,0.498527,-1.087415
202022,3465.059937,11934.184505,3.444150,0.537082,-0.711723
202023,10738.134779,20641.386924,1.922251,0.283810,0.919399
202024,14630.390786,26787.880643,1.830975,0.262682,0.395578
202025,14526.963734,29512.255290,2.031550,0.307828,-0.016018
202026,20637.352089,31820.902370,1.541908,0.188059,0.662074
202027,19402.503969,32728.823124,1.686835,0.227073,-0.082552
202028,22320.436181,32531.939652,1.457496,0.163607,0.135898
202029,22066.191118,32793.482089,1.486141,0.172060,0.018892
202030,17598.251610,24421.198616,1.387706,0.142297,0.031166
202031,17596.843929,26102.227859,1.483347,0.171243,-0.385055
202032,20967.555583,30786.372140,1.468286,0.166811,-0.024775
202033,17217.502602,36492.334081,2.119491,0.326231,-1.299196
202034,14995.371811,27867.763435,1.858424,0.269145,-0.356886
202035,12527.980909,28569.750673,2.280475,0.358025,-1.425905
202036,13225.075019,40590.363878,3.069197,0.487025,-1.713063
202037,5032.181665,13872.765198,2.756809,0.440407,-0.643939
202038,9616.043852,24227.457498,2.519483,0.401311,-0.022191
202039,6788.058200,23263.569019,3.427132,0.534931,-0.681354
202040,4102.169413,15317.370047,3.733968,0.572171,-0.953421

In [144]:
stdBW_dir = "/work/tadesse/beichen/Work/ForestDri/Ameriflux/Bowen_Ratio/"
stdBW_list = glob.glob(stdBW_dir+"US*_stdBW.csv")
stdBW_list.sort()
for stdBW in stdBW_list:
    df = pd.read_csv(stdBW)
    print(df.head())

   Unnamed: 0  LE   H  Bowen_ratio  Log_Bowen_ratio  STD_Log_Bowen_ratio
0      200101 NaN NaN          NaN              NaN                  NaN
1      200102 NaN NaN          NaN              NaN                  NaN
2      200103 NaN NaN          NaN              NaN                  NaN
3      200104 NaN NaN          NaN              NaN                  NaN
4      200105 NaN NaN          NaN              NaN                  NaN
   Unnamed: 0  LE   H  Bowen_ratio  Log_Bowen_ratio  STD_Log_Bowen_ratio
0      200401 NaN NaN          NaN              NaN                  NaN
1      200402 NaN NaN          NaN              NaN                  NaN
2      200403 NaN NaN          NaN              NaN                  NaN
3      200404 NaN NaN          NaN              NaN                  NaN
4      200405 NaN NaN          NaN              NaN                  NaN
   Unnamed: 0       LE        H  Bowen_ratio  Log_Bowen_ratio  \
0      200201      NaN      NaN          NaN              NaN
1      200202   827.72   977.06     1.180423         0.072038
2      200203   368.22   768.16     2.086144         0.319344
3      200204  1253.20  1473.19     1.175543         0.070238
4      200205   936.94  1039.34     1.109292         0.045046

   STD_Log_Bowen_ratio
0                  NaN
1            -0.072964
2            -0.908814
3             0.476900
4             1.288252
   Unnamed: 0          LE            H  Bowen_ratio  Log_Bowen_ratio  \
0      200801         NaN          NaN          NaN              NaN
1      200802  101.534570    70.967538     0.698950        -0.155554
2      200803         NaN          NaN          NaN              NaN
3      200804         NaN          NaN          NaN              NaN
4      200805  718.683758  1844.403241     2.566363         0.409318

   STD_Log_Bowen_ratio
0                  NaN
1             2.663038
2                  NaN
3                  NaN
4             1.302637
   Unnamed: 0  LE   H  Bowen_ratio  Log_Bowen_ratio  STD_Log_Bowen_ratio
0      199801 NaN NaN          NaN              NaN                  NaN
1      199802 NaN NaN          NaN              NaN                  NaN
2      199803 NaN NaN          NaN              NaN                  NaN
3      199804 NaN NaN          NaN              NaN                  NaN
4      199805 NaN NaN          NaN              NaN                  NaN
   Unnamed: 0         LE          H  Bowen_ratio  Log_Bowen_ratio  \
0      200401        NaN        NaN          NaN              NaN
1      200402   117.0937   276.4000     2.360503         0.373005
2      200403   666.0834  2138.7337     3.210910         0.506628
3      200404  2278.7557  4906.8179     2.153288         0.333102
4      200405   955.1862  2664.3378     2.789339         0.445501

   STD_Log_Bowen_ratio
0                  NaN
1             0.161075
2            -0.684442
3            -0.103014
4             0.150070
   Unnamed: 0           LE         H  Bowen_ratio  Log_Bowen_ratio  \
0      200701          NaN       NaN          NaN              NaN
1      200702   792.631913  1563.753     1.972862         0.295097
2      200703          NaN       NaN          NaN              NaN
3      200704  1004.328062  2104.799     2.095729         0.321335
4      200705   559.366944   981.206     1.754137         0.244063

   STD_Log_Bowen_ratio
0                  NaN
1            -0.444246
2                  NaN
3            -0.684979
4             0.571692
   Unnamed: 0  LE   H  Bowen_ratio  Log_Bowen_ratio  STD_Log_Bowen_ratio
0      200101 NaN NaN          NaN              NaN                  NaN
1      200102 NaN NaN          NaN              NaN                  NaN
2      200103 NaN NaN          NaN              NaN                  NaN
3      200104 NaN NaN          NaN              NaN                  NaN
4      200105 NaN NaN          NaN              NaN                  NaN
   Unnamed: 0  LE   H  Bowen_ratio  Log_Bowen_ratio  STD_Log_Bowen_ratio
0      200301 NaN NaN          NaN              NaN                  NaN
1      200302 NaN NaN          NaN              NaN                  NaN
2      200303 NaN NaN          NaN              NaN                  NaN
3      200304 NaN NaN          NaN              NaN                  NaN
4      200305 NaN NaN          NaN              NaN                  NaN
   Unnamed: 0           LE            H  Bowen_ratio  Log_Bowen_ratio  \
0      200701  2551.311415  6139.507227     2.406412         0.381370
1      200702    75.810299   187.633540     2.475040         0.393582
2      200703  2408.962791  6014.099710     2.496552         0.397341
3      200704  2280.115512  3423.546813     1.501480         0.176519
4      200705  4061.259804  7526.961671     1.853356         0.267959

   STD_Log_Bowen_ratio
0            -0.176125
1            -0.493939
2             0.070618
3             0.131043
4             0.149832
   Unnamed: 0           LE            H  Bowen_ratio  Log_Bowen_ratio  \
0      200701  1694.620551  5626.316318     3.320104         0.521152
1      200702   562.055928  1421.857456     2.529744         0.403077
2      200703  1321.706073  4807.157551     3.637085         0.560753
3      200704  2066.473201  6821.687291     3.301125         0.518662
4      200705  2363.338061  7474.071891     3.162506         0.500031

   STD_Log_Bowen_ratio
0            -0.871628
1             0.435199
2            -0.399460
3            -0.634588
4             0.245956
   Unnamed: 0  LE   H  Bowen_ratio  Log_Bowen_ratio  STD_Log_Bowen_ratio
0      200701 NaN NaN          NaN              NaN                  NaN
1      200702 NaN NaN          NaN              NaN                  NaN
2      200703 NaN NaN          NaN              NaN                  NaN
3      200704 NaN NaN          NaN              NaN                  NaN
4      200705 NaN NaN          NaN              NaN                  NaN
   Unnamed: 0  LE   H  Bowen_ratio  Log_Bowen_ratio  STD_Log_Bowen_ratio
0      200701 NaN NaN          NaN              NaN                  NaN
1      200702 NaN NaN          NaN              NaN                  NaN
2      200703 NaN NaN          NaN              NaN                  NaN
3      200704 NaN NaN          NaN              NaN                  NaN
4      200705 NaN NaN          NaN              NaN                  NaN
   Unnamed: 0  LE   H  Bowen_ratio  Log_Bowen_ratio  STD_Log_Bowen_ratio
0      199801 NaN NaN          NaN              NaN                  NaN
1      199802 NaN NaN          NaN              NaN                  NaN
2      199803 NaN NaN          NaN              NaN                  NaN
3      199804 NaN NaN          NaN              NaN                  NaN
4      199805 NaN NaN          NaN              NaN                  NaN